# Header
menu:
  Home: /
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: bottom
widgets:
- page # n existe pas mais il ne faut pas que ce soit vide
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: